"""Fix bad realtionships

Revision ID: 028b4ed2d9b0
Revises: 5fda11fc7d45
Create Date: 2024-03-21 16:34:37.674595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028b4ed2d9b0'
down_revision: Union[str, None] = '5fda11fc7d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
