"""Add deleting all row with cascade

Revision ID: 3de1c7d046ec
Revises: 3385c35d23b6
Create Date: 2024-03-21 18:54:46.911950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de1c7d046ec'
down_revision: Union[str, None] = '3385c35d23b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
