"""Fix bug with bad relationship with Travel and TravelNote

Revision ID: 907bc50b691b
Revises: fff233f9de4f
Create Date: 2024-03-20 16:16:08.087937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907bc50b691b'
down_revision: Union[str, None] = 'fff233f9de4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
