"""Fix bad relationships

Revision ID: b8254bb3cf95
Revises: 2376f67a4023
Create Date: 2024-03-25 19:55:09.194958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8254bb3cf95'
down_revision: Union[str, None] = '2376f67a4023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_notes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_travel_notes_owner_id'), 'travel_notes', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'travel_notes', 'users', ['owner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travel_notes', type_='foreignkey')
    op.drop_index(op.f('ix_travel_notes_owner_id'), table_name='travel_notes')
    op.drop_column('travel_notes', 'owner_id')
    # ### end Alembic commands ###
