"""Rename columns in travel_notes table

Revision ID: e00c2ff6919f
Revises: 907bc50b691b
Create Date: 2024-03-20 21:03:09.499672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00c2ff6919f'
down_revision: Union[str, None] = '907bc50b691b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_notes', sa.Column('attached_file', sa.String(), nullable=True))
    op.drop_column('travel_notes', 'attachment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_notes', sa.Column('attachment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('travel_notes', 'attached_file')
    # ### end Alembic commands ###
