"""Add travels and travel_cities tables

Revision ID: e69516c659f3
Revises: ffac3c726bd8
Create Date: 2024-03-18 18:42:26.405239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69516c659f3'
down_revision: Union[str, None] = 'ffac3c726bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_user_travel_name')
    )
    op.create_index(op.f('ix_travels_id'), 'travels', ['id'], unique=False)
    op.create_index(op.f('ix_travels_owner_id'), 'travels', ['owner_id'], unique=False)
    op.create_table('travel_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_cities_id'), 'travel_cities', ['id'], unique=False)
    op.create_index(op.f('ix_travel_cities_travel_id'), 'travel_cities', ['travel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_cities_travel_id'), table_name='travel_cities')
    op.drop_index(op.f('ix_travel_cities_id'), table_name='travel_cities')
    op.drop_table('travel_cities')
    op.drop_index(op.f('ix_travels_owner_id'), table_name='travels')
    op.drop_index(op.f('ix_travels_id'), table_name='travels')
    op.drop_table('travels')
    # ### end Alembic commands ###
