"""Add travel notes table

Revision ID: fff233f9de4f
Revises: bc7fd076dcaf
Create Date: 2024-03-20 15:53:12.815644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff233f9de4f'
down_revision: Union[str, None] = 'bc7fd076dcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_notes_id'), 'travel_notes', ['id'], unique=False)
    op.create_index(op.f('ix_travel_notes_travel_id'), 'travel_notes', ['travel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_notes_travel_id'), table_name='travel_notes')
    op.drop_index(op.f('ix_travel_notes_id'), table_name='travel_notes')
    op.drop_table('travel_notes')
    # ### end Alembic commands ###
